### ISSUE TITLE
opal host won't save location of VLC

### ISSUE THREAD

**Issue by TBspot** [pyarmak/OPAL-Helper-Host#2]
64bit windows 10 pro
google chrome

![image](https://user-images.githubusercontent.com/32471463/31105162-9cf696fc-a7a7-11e7-88bb-68873a628b31.png)
The screenshot above shows where to input directory info for VLC location. After ticking the box and pasting it in, then closing the dialogue window (there is no save button) and reopening the settings dialogue, the fields are blank. In short, the extension won't save the file locations inputted. Destination being used is "C:\Program Files (x86)\VideoLAN\VLC\vlc.exe" without the quotations, and no trailing space. 

Thanks for your hard work Pavel, you're helping keep us sane!

**Comment by pyarmak** [comment]
Thanks for letting me know about this!

I fixed it in the other repository (it was an extension issue that didn't require a host application update).
